### Register User Bayu
POST http://localhost:5000/register
Content-Type: application/json

{
  "username": "bayu",
  "email": "bayu@example.com",
  "password": "password123"
}

###

### Login User Bayu
POST http://localhost:5000/login
Content-Type: application/json

{
  "usernameOrEmail": "detri",
  "password": "123"
}

###

### Ambil Semua Kategori
GET http://localhost:5000/categories
Authorization: Bearer <accessToken>

###

### Buat Kategori Baru
POST http://localhost:5000/categories
Content-Type: application/json
Authorization: Bearer <accessToken>

{
  "name": "TCC"
}

###

### Buat Task Baru
POST http://localhost:5000/tasks
Content-Type: application/json
Authorization: Bearer <accessToken>

{
  "title": "Belajar Node.js",
  "description": "Pelajari dasar express dan sequelize",
  "deadline": "2025-06-01",
  "categoryId": 1
}

###

### Ambil Semua Task User
GET http://localhost:5000/tasks
Authorization: Bearer <accessToken>

###

### Update Task by ID (ganti :id dengan ID task yang ingin diupdate)
PUT http://localhost:5000/tasks/:id
Content-Type: application/json
Authorization: Bearer <accessToken>

{
  "title": "Belajar Node.js Lanjutan",
  "description": "Pelajari express middleware",
  "status": "completed",
  "deadline": "2025-06-05",
  "categoryId": 1
}

###

### Hapus Task by ID (ganti :id dengan ID task yang ingin dihapus)
DELETE http://localhost:5000/tasks/:id
Authorization: Bearer <accessToken>

###

### Ambil Statistik Task User (Dashboard)
GET http://localhost:5000/tasks/statistics
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwidXNlcm5hbWUiOiJkZXRyaSIsImlhdCI6MTc0ODY3NzE5MiwiZXhwIjoxNzQ4Njc4MDkyfQ.VqHA8ly50B5i3YZN01okRzExUN3sBRCIMgHXw5drt8A
###
